// Copyright 2026 The Graft Authors

// Package lockfile reads and writes the auto-generated graft.lock file
// (spec §3.2): the resolved, pinned state that `graft apply` installs from.
package lockfile

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/BurntSushi/toml"
	"github.com/min0625/graft/internal/clierr"
)

// Filename is the lockfile name, next to graft.toml in the project root.
const Filename = "graft.lock"

// Version is the only lock_version this graft understands.
// Bumped from 1 to 2 when exec-bit inclusion in the hash was introduced
// (spec §3.2, decision §10.14), invalidating all v1 lockfiles.
const Version = 2

// header precedes the TOML body in every written lockfile.
const header = `# This file is auto-generated by graft. Do not edit manually.
# Run ` + "`graft lock`" + ` to regenerate.

`

// Lockfile represents graft.lock.
type Lockfile struct {
	LockVersion int         `toml:"lock_version"`
	Dir         string      `toml:"dir"` // install root, copied from graft.toml
	Deps        []LockedDep `toml:"deps,omitempty"`
}

// LockedDep is one [[deps]] entry of the lockfile.
type LockedDep struct {
	Name    string    `toml:"name"`
	Repo    string    `toml:"repo"`
	Version string    `toml:"version"`        // sync key, copied verbatim from graft.toml
	Path    string    `toml:"path,omitempty"` // subdirectory of the remote repo
	Commit  string    `toml:"commit"`         // full SHA the version resolved to at lock time
	Time    time.Time `toml:"time"`           // committer timestamp of the commit (UTC)
	Hash    string    `toml:"hash"`           // sha256 of content tree
}

// Dest returns d's install path relative to the project root, slash-separated:
// <vendor>/<name>. The lockfile stores vendor once at the top level, so the
// per-dep install path is derived from it and the dep's name (spec §3.2).
func (l *Lockfile) Dest(d LockedDep) string {
	return path.Join(l.Dir, d.Name)
}

// New returns an empty lockfile of the current version.
func New() *Lockfile {
	return &Lockfile{LockVersion: Version}
}

// Load reads and parses the lockfile at path. A missing file is reported as
// fs.ErrNotExist so callers can give command-specific hints.
func Load(path string) (*Lockfile, error) {
	data, err := os.ReadFile(path) //nolint:gosec // The path is the project's own graft.lock.
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, err
		}

		return nil, clierr.New(clierr.CodeConfig,
			"cannot read "+Filename,
			err.Error(),
		)
	}

	var lf Lockfile

	meta, err := toml.Decode(string(data), &lf)
	if err != nil {
		return nil, clierr.New(clierr.CodeConfig,
			"invalid "+Filename,
			err.Error(),
			"run `graft lock` to regenerate it",
		)
	}

	if lf.LockVersion != Version {
		return nil, clierr.New(clierr.CodeConfig,
			fmt.Sprintf("unsupported lock_version %d in %s", lf.LockVersion, Filename),
			"this version of graft only understands lock_version "+strconv.Itoa(Version),
			"upgrade graft, or run `graft lock` to regenerate the lockfile",
		)
	}

	if undecoded := meta.Undecoded(); len(undecoded) > 0 {
		keys := make([]string, len(undecoded))
		for i, k := range undecoded {
			keys[i] = k.String()
		}

		return nil, clierr.New(clierr.CodeConfig,
			"invalid "+Filename,
			"unknown key(s): "+strings.Join(keys, ", "),
			"run `graft lock` to regenerate it",
		)
	}

	if lf.Dir == "" {
		return nil, clierr.New(clierr.CodeConfig,
			"invalid "+Filename,
			`the required "dir" field is missing`,
			"run `graft lock` to regenerate it",
		)
	}

	return &lf, nil
}

// FindDep returns a pointer to the locked dep named name, or nil.
func (l *Lockfile) FindDep(name string) *LockedDep {
	for i := range l.Deps {
		if l.Deps[i].Name == name {
			return &l.Deps[i]
		}
	}

	return nil
}

// Encode renders the lockfile deterministically: a fixed header, fields in
// struct order, entries sorted by name, and times in UTC — so regenerating
// an unchanged lockfile is byte-identical.
func (l *Lockfile) Encode() ([]byte, error) {
	sorted := *l
	sorted.Deps = slices.Clone(l.Deps)

	slices.SortFunc(sorted.Deps, func(a, b LockedDep) int {
		return strings.Compare(a.Name, b.Name)
	})

	for i := range sorted.Deps {
		sorted.Deps[i].Time = sorted.Deps[i].Time.UTC()
	}

	var b strings.Builder

	b.WriteString(header)

	enc := toml.NewEncoder(&b)
	enc.Indent = ""

	if err := enc.Encode(sorted); err != nil {
		return nil, fmt.Errorf("encode %s: %w", Filename, err)
	}

	return []byte(b.String()), nil
}

// Write encodes the lockfile and writes it to path.
func (l *Lockfile) Write(path string) error {
	data, err := l.Encode()
	if err != nil {
		return err
	}

	if err := os.WriteFile(path, data, 0o644); err != nil { //nolint:gosec // The lockfile is committed, world-readable.
		return fmt.Errorf("write %s: %w", Filename, err)
	}

	return nil
}
