// Copyright 2026 The Graft Authors

package lockfile_test

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/min0625/graft/internal/clierr"
	"github.com/min0625/graft/internal/lockfile"
)

func sample() *lockfile.Lockfile {
	return &lockfile.Lockfile{
		LockVersion: lockfile.Version,
		Dir:         "vendor",
		Deps: []lockfile.LockedDep{
			{
				Name:    "proto-defs",
				Repo:    "github.com/org/proto-defs",
				Version: "v0.8.1",
				Path:    "proto",
				Commit:  "b7e1209fa3c8d2e1f0a9b8c7d6e5f4a3b2c1d0e9",
				Time:    time.Date(2026, 2, 2, 18, 40, 11, 0, time.UTC),
				Hash:    "sha256:a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3",
			},
			{
				Name:    "shared-scripts",
				Repo:    "github.com/org/shared-scripts",
				Version: "v1.2.0",
				Commit:  "a3f8c21d4e8f1b2c3d4e5f6a7b8c9d0e1f2a3b4c",
				Time:    time.Date(2026, 4, 18, 9, 13, 27, 0, time.UTC),
				Hash:    "sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			},
		},
	}
}

func TestRoundTrip(t *testing.T) {
	t.Parallel()

	want := sample()
	path := filepath.Join(t.TempDir(), lockfile.Filename)

	if err := want.Write(path); err != nil {
		t.Fatal(err)
	}

	got, err := lockfile.Load(path)
	if err != nil {
		t.Fatal(err)
	}

	if got.LockVersion != want.LockVersion || got.Dir != want.Dir || len(got.Deps) != len(want.Deps) {
		t.Fatalf("round trip mismatch: %+v", got)
	}

	for i := range want.Deps {
		w, g := want.Deps[i], got.Deps[i]
		if !g.Time.Equal(w.Time) {
			t.Errorf("Deps[%d].Time = %v, want %v", i, g.Time, w.Time)
		}

		g.Time = w.Time
		if g != w {
			t.Errorf("Deps[%d] = %+v, want %+v", i, g, w)
		}
	}
}

func TestEncode_deterministic(t *testing.T) {
	t.Parallel()

	a, err := sample().Encode()
	if err != nil {
		t.Fatal(err)
	}

	// Same content with shuffled entry order and a non-UTC time must encode
	// byte-identically.
	shuffled := sample()
	shuffled.Deps[0], shuffled.Deps[1] = shuffled.Deps[1], shuffled.Deps[0]
	shuffled.Deps[0].Time = shuffled.Deps[0].Time.In(time.FixedZone("UTC+8", 8*3600))

	b, err := shuffled.Encode()
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(a, b) {
		t.Errorf("encodings differ:\n%s\n---\n%s", a, b)
	}
}

func TestEncode_headerAndOmittedPath(t *testing.T) {
	t.Parallel()

	data, err := sample().Encode()
	if err != nil {
		t.Fatal(err)
	}

	text := string(data)

	if !strings.HasPrefix(text, "# This file is auto-generated by graft. Do not edit manually.\n") {
		t.Errorf("missing header:\n%s", text)
	}

	if !strings.Contains(text, "lock_version = 2\n") {
		t.Errorf("missing lock_version:\n%s", text)
	}

	// shared-scripts has no path; its entry must not contain a path key.
	if strings.Count(text, "path = ") != 1 {
		t.Errorf("want exactly one path key (proto-defs only):\n%s", text)
	}
}

func TestWrite_regenerateIsByteIdentical(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), lockfile.Filename)

	if err := sample().Write(path); err != nil {
		t.Fatal(err)
	}

	first, err := os.ReadFile(path) //nolint:gosec // Test-controlled path.
	if err != nil {
		t.Fatal(err)
	}

	loaded, err := lockfile.Load(path)
	if err != nil {
		t.Fatal(err)
	}

	if err := loaded.Write(path); err != nil {
		t.Fatal(err)
	}

	second, err := os.ReadFile(path) //nolint:gosec // Test-controlled path.
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(first, second) {
		t.Errorf("regenerated lockfile differs:\n%s\n---\n%s", first, second)
	}
}

func TestLoad_missingFile(t *testing.T) {
	t.Parallel()

	_, err := lockfile.Load(filepath.Join(t.TempDir(), lockfile.Filename))
	if !errors.Is(err, fs.ErrNotExist) {
		t.Fatalf("err = %v, want fs.ErrNotExist", err)
	}
}

func TestLoad_unsupportedVersion(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), lockfile.Filename)
	if err := os.WriteFile(path, []byte("lock_version = 99\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	_, err := lockfile.Load(path)
	if got := clierr.ExitCode(err); got != int(clierr.CodeConfig) {
		t.Fatalf("exit code = %d, want %d (error: %v)", got, clierr.CodeConfig, err)
	}
}

func TestFindDep(t *testing.T) {
	t.Parallel()

	lf := sample()

	if d := lf.FindDep("shared-scripts"); d == nil || d.Version != "v1.2.0" {
		t.Errorf("FindDep(shared-scripts) = %+v", d)
	}

	if d := lf.FindDep("nope"); d != nil {
		t.Errorf("FindDep(nope) = %+v, want nil", d)
	}
}

// TestRoundTrip_sha256Commit verifies that a LockedDep with a 64-character
// SHA-256 commit hash round-trips through Write/Load unchanged.
// spec: REQ-LOCK-SHA256-COMMIT
func TestRoundTrip_sha256Commit(t *testing.T) {
	t.Parallel()

	lf := sample()
	lf.Deps[0].Commit = "b7e1209fa3c8d2e1f0a9b8c7d6e5f4a3b2c1d0e9b7e1209fa3c8d2e1f0a9b8c7"

	path := filepath.Join(t.TempDir(), lockfile.Filename)
	if err := lf.Write(path); err != nil {
		t.Fatalf("Write: %v", err)
	}

	got, err := lockfile.Load(path)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if got.Deps[0].Commit != lf.Deps[0].Commit {
		t.Errorf("Commit = %q, want %q", got.Deps[0].Commit, lf.Deps[0].Commit)
	}
}
